name: 'hevy_dbt'
version: '1.0.0'
config-version: 2

profile: 'hevy_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  hevy_dbt:
    +schema: BRONZE
    muscle_landmarks:
      +column_types:
        muscle: VARCHAR
        movement_group: VARCHAR
        mev_sets: NUMBER(3,0)
        mav_sets: NUMBER(3,0)
        mrv_sets: NUMBER(3,0)

models:
  hevy_dbt:
    silver:
      +schema: SILVER
      +materialized: incremental
    gold:
      +schema: GOLD
      +materialized: table